const actions = {
  "GET_USER_FRIENDS": "GET_USER_FRIENDS",
  "GET_USER_LIKES": "GET_USER_LIKES",
  "GET_USER_PROFILE": "GET_USER_PROFILE",
  "SAVE_USER_CREDENTIALS": "SAVE_USER_CREDENTIALS"
};

export default actions;
