const actions = {
  "GET_USER_DETAILS": "GET_USER_DETAILS",
  "GET_USER_FRIENDS": "GET_USER_FRIENDS",
  "GET_USER_LIKES": "GET_USER_LIKES",
  "GET_USER_PICTURE": "GET_USER_PICTURE",
  "SAVE_USER_CREDENTIALS": "SAVE_USER_CREDENTIALS"
};

export default actions;
